# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

In [1]:
import numpy as np
import random

In [2]:
# use routine to create randomly filled matrices whenever appropriate
def populate(matrix):
    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
    return matrix

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [3]:
# The "Distributive Law" says, we get the same answer when we: 
# a) multiply a number by a group of numbers added together, or
# b) do each multiply separately then add them.

# The "Distributive Law" does not work for division!

In [4]:
# create zero-arrays
zero = np.zeros((4,4))

# call function to fill arrays with random numbers
A = populate(zero)
B = populate(zero)
C = populate(zero)

# perform operations
dist_1 = A.dot(B + C)
dist_2 = A.dot(B) + A.dot(C)

# prove both results are the same
print(dist_1 == dist_2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [5]:
# The "Associative Law" saya that it doesn't matter how we group the numbers (i.e. which we calculate first).

# The "Associative Law" does not work for subtraction or division!

In [6]:
# create zero-arrays
zero = np.zeros((4,4))

# call function to fill arrays with random numbers
A = populate(zero)
B = populate(zero)
C = populate(zero)

# perform operations
asso_1 = A.dot(B.dot(C))
asso_2 = A.dot(B).dot(C)

# prove both results are the same
print(asso_1 == asso_2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [7]:
# The "Commutative Law" says we can swap numbers over and still get the same answer when we simply add or multiply.
# Why "commutative" ... ? Because the numbers can travel back and forth like a commuter.

# The "Commutative Law" does not work for subtraction or division!
# And it holds not true for matrix multiplication!

In [8]:
A = np.array([[2, 3], [6, 5]])
B = np.array([[5, 3], [2, 2]])

# perform operations
comm_1 = A.dot(B)
comm_2 = B.dot(A)

# prove both results are not the same
comm_1 != comm_2

array([[ True,  True],
       [ True,  True]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [9]:
# create zero vectors
zero = np.zeros((3,1))

# call function to fill arrays with random numbers
x = populate(zero)
y = populate(zero)

# perform operations
vec_mult_1 = np.transpose(x).dot(y)
vec_mult_2 = np.transpose(y).dot(x)

# prove both results are the same
vec_mult_1 == vec_mult_2

array([[ True]])

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [10]:
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5, 3], [2, 2]])

# perform operations
left = np.transpose(A.dot(B))
right = np.transpose(B).dot(np.transpose(A))

# prove both results are the same
left == right

array([[ True,  True,  True],
       [ True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 